<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kadath.Editor.Workspace</AssemblyName>
    <RootNamespace>Kadath.Editor.Workspace</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kadath.Editor.Protocol\Kadath.Editor.Protocol.csproj" />
  </ItemGroup>
</Project>
