<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Kadath.Editor.Toolchain</AssemblyName>
    <RootNamespace>Kadath.Editor.Toolchain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kadath.Editor.Workspace\Kadath.Editor.Workspace.csproj" />
  </ItemGroup>
</Project>
