#ifndef KADATH_ERRORS_H
#define KADATH_ERRORS_H

#include <stdint.h>

#define KADATH_OK 0

#define KADATH_ERR_INVALID_ARGUMENT 0x0001
#define KADATH_ERR_OUT_OF_MEMORY 0x0002
#define KADATH_ERR_BUFFER_TOO_SMALL 0x0003
#define KADATH_ERR_NOT_FOUND 0x0004
#define KADATH_ERR_NOT_SUPPORTED 0x0005
#define KADATH_ERR_INTERNAL 0x0006

#define KADATH_ERR_WORLD_BASE 0x4000
#define KADATH_ERR_WORLD_INVALID_ENTITY (KADATH_ERR_WORLD_BASE + 0x0001)

#define KADATH_ERR_SCHEDULER_BASE 0x5000
#define KADATH_ERR_SCHEDULER_INVALID_KEY (KADATH_ERR_SCHEDULER_BASE + 0x0001)
#define KADATH_ERR_SCHEDULER_INVALID_STATE (KADATH_ERR_SCHEDULER_BASE + 0x0002)
#define KADATH_ERR_SCHEDULER_AT_CAPACITY (KADATH_ERR_SCHEDULER_BASE + 0x0003)
#define KADATH_ERR_SCHEDULER_WORKER_UNAVAILABLE (KADATH_ERR_SCHEDULER_BASE + 0x0004)
#define KADATH_ERR_SCHEDULER_JOB_ID_EXHAUSTED (KADATH_ERR_SCHEDULER_BASE + 0x0005)
#define KADATH_ERR_SCHEDULER_WORKER_PANICKED (KADATH_ERR_SCHEDULER_BASE + 0x0006)
#define KADATH_ERR_SCHEDULER_ALLOCATION_FAILED (KADATH_ERR_SCHEDULER_BASE + 0x0007)

#endif
