#ifndef KADATH_ERRORS_H
#define KADATH_ERRORS_H

#include <stdint.h>

#define KADATH_OK 0

#define KADATH_ERR_INVALID_ARGUMENT 0x0001
#define KADATH_ERR_OUT_OF_MEMORY 0x0002
#define KADATH_ERR_BUFFER_TOO_SMALL 0x0003
#define KADATH_ERR_NOT_FOUND 0x0004
#define KADATH_ERR_NOT_SUPPORTED 0x0005
#define KADATH_ERR_INTERNAL 0x0006

#define KADATH_ERR_WORLD_BASE 0x4000
#define KADATH_ERR_WORLD_INVALID_ENTITY (KADATH_ERR_WORLD_BASE + 0x0001)

#define KADATH_ERR_RUNTIME_BASE KADATH_ERR_WORLD_BASE
#define KADATH_ERR_RUNTIME_WRONG_THREAD 0x4101
#define KADATH_ERR_RUNTIME_REENTRANT 0x4102
#define KADATH_ERR_RUNTIME_INVALID_STATE 0x4103
#define KADATH_ERR_RUNTIME_CANDIDATE_BUSY 0x4104
#define KADATH_ERR_RUNTIME_STALE_OBJECT 0x4105
#define KADATH_ERR_RUNTIME_SOURCE_DESTROY_REJECTED 0x4106
#define KADATH_ERR_RUNTIME_OBJECT_CAPACITY 0x4107
#define KADATH_ERR_RUNTIME_INVALID_LIFECYCLE 0x4108
#define KADATH_ERR_RUNTIME_TRANSIENT_ID_EXHAUSTED 0x4109
#define KADATH_ERR_RUNTIME_EPOCH_EXHAUSTED 0x410A
#define KADATH_ERR_RUNTIME_DUPLICATE_OBJECT_ID 0x410B

#define KADATH_ERR_SCHEDULER_BASE 0x5000
#define KADATH_ERR_SCHEDULER_INVALID_KEY (KADATH_ERR_SCHEDULER_BASE + 0x0001)
#define KADATH_ERR_SCHEDULER_INVALID_STATE (KADATH_ERR_SCHEDULER_BASE + 0x0002)
#define KADATH_ERR_SCHEDULER_AT_CAPACITY (KADATH_ERR_SCHEDULER_BASE + 0x0003)
#define KADATH_ERR_SCHEDULER_WORKER_UNAVAILABLE (KADATH_ERR_SCHEDULER_BASE + 0x0004)
#define KADATH_ERR_SCHEDULER_JOB_ID_EXHAUSTED (KADATH_ERR_SCHEDULER_BASE + 0x0005)
#define KADATH_ERR_SCHEDULER_WORKER_PANICKED (KADATH_ERR_SCHEDULER_BASE + 0x0006)
#define KADATH_ERR_SCHEDULER_ALLOCATION_FAILED (KADATH_ERR_SCHEDULER_BASE + 0x0007)

#endif
